# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('day', models.CharField(default='N/A', max_length=10)),
                ('subject_order', models.IntegerField(default=0)),
                ('subject_name', models.CharField(default='N/A', max_length=50)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.UsersGroup')),
            ],
        ),
    ]
